source 'http://rubygems.org'
gem 'sinatra'
gem 'datamapper'
gem 'dm-sqlite-adapter'
gem 'dm-postgres-adapter'
gem 'dm-timestamps'
gem 'dm-aggregates'
gem 'dm-constraints'
gem 'dm-core'
gem 'dm-transactions'
gem 'dm-transactions'
gem 'dm-types'
gem 'dm-validations'
gem 'pony'
gem 'twitter_oauth'

